### ISSUE TITLE
Dojo loader issue with the print widget

### ISSUE THREAD

**Issue by Alex9200** [DavidSpriggs/print-widget-js#1]
Hi,
First off, I love this widget and it is exactly what I am looking for.
However I noticed a small bug. Once in a while, the dojo loader fails and It stops all the API process to load the map in the browser. Any idea why?
Here is a screen shot of the error I get:
![image](https://cloud.githubusercontent.com/assets/11637949/12433179/6a81c846-beb4-11e5-9db0-13a17d811f86.png)
https://geonet.esri.com/servlet/JiveServlet/download/578843-152350/Capture.PNG
Thanks,
Alex

**Comment by DavidSpriggs** [comment]
The old dbootstrap css.js was problematic. We dumped it a while back and went to a pure css dbootstrap. You can switch to using it as well with this widget. Find the new pure css here: 
https://github.com/cmv/cmv-app/tree/master/viewer/css/theme
